name: com_celesoft_notasieo
description: Servicio Académico Ie de Occidente.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  localstorage: ^4.0.0+1
  http: ^1.0.0
  dio: ^5.3.2
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  easy_splash_screen: ^1.0.4
  icons_launcher: ^2.1.3
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  desktop_window: ^0.4.0
  logger: ^2.0.2+1
  fluttertoast: ^8.2.4
  flutter_drawing_board: ^0.7.0+2
  path_provider: ^2.0.2
  device_info_plus: ^10.0.1
  flutter_localization: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true


icons_launcher:
  image_path: "assets/icons/android-icon-96x96.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true